version: "3.8"

services:
  dind:
    image: docker:dind
    privileged: true
    restart: always
    networks:
      jenkin-network:
        aliases:
          - docker
    ports:
      - 2376:2376
    tty: true
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client
    environment:
      - DOCKER_TLS_CERTDIR=/certs

  jenkins:
    build:
      context: .
      dockerfile: Dockerfile

    restart: always
    networks:
      - jenkin-network
    ports:
      - 8443:8080
      - 50000:50000
    tty: true
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/cient:ro
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    depends_on:
      - dind

networks:
  jenkin-network:

volumes:
  jenkins-data:
  jenkins-docker-certs:
