apiVersion: v1
kind: Service
metadata:
  name: webapp
  labels:
    app: webapp
    tier: backend
spec:
  type: NodePort
  selector:
    app: webapp
    tier: backend
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30006
