apiVersion: v1
kind: Pod
metadata:
  name: mysql-pvc
  labels:
    app: db
spec:
  containers:
    - name: mysqldb
      image: mysql-db:latest
      imagePullPolicy: Never
      volumeMounts:
        - name: mysql-pd
          mountPath: /var/lib/mysql
      resources:
        limits:
          memory: "500Mi"
          cpu: "500m"
      ports:
        - containerPort: 3306
  volumes:
    - name: mysql-pd
      persistentVolumeClaim:
        claimName: mysql-pv-claim
