version: "3.8"
services:
  registry:
    image: registry:2.7
    volumes:
      - ./registry-data:/var/lib/registry
    ports:
      - 5000:5000
    networks:
      - registry-ui-net

  ui:
    image: joxit/docker-registry-ui:latest
    ports:
      - 8888:80
    environment:
      - REGISTRY_TITLE=Docker Registry
      - NGINX_PROXY_PASS_URL=http://registry:5000
      - SINGLE_REGISTRY=true
      - SHOW_CONTENT_DIGEST=true
      - DELETE_IMAGES=true
    depends_on:
      - registry
    networks:
      - registry-ui-net

networks:
  registry-ui-net:
